services:
#  exchange-app:
#    build: .
#    ports:
#      - 8081:8081

  db:
    ports:
      - 5431:5432
    container_name: postgresql_exchange
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq_exchange
    ports:
      - 5671:5672
      - 15671:15672
    restart: always

volumes:
  pgdata:
    driver: local
