services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_broker
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq_broker
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
volumes:
  pgdata:
    driver: local
